version: '3'

volumes:
  pg_data:
  static:
  media:
  data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ivnio/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media
      - ./data:/app/data
  frontend:
    image: ivnio/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: ivnio/foodgram_gateway:latest
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/var/www/media
      - ./docs:/usr/share/nginx/html/api
